name: CD - Deploy Infrastructure

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/ci.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Package Lambda functions
        run: |
          # Package processFile Lambda
          cd src/processFile
          npm ci --production || npm install --production
          zip -r processFile.zip .
          
          # Package getMessage Lambda
          cd ../getMessage
          npm ci --production || npm install --production
          zip -r getMessage.zip .

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Initialize Terraform
        working-directory: infra/terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: infra/terraform
        run: terraform apply -auto-approve

      - name: Display deployment information
        working-directory: infra/terraform
        run: |
          echo "API Endpoint: $(terraform output -raw api_endpoint 2>/dev/null || echo 'Not available')"
          echo "S3 Bucket: $(terraform output -raw upload_bucket_name 2>/dev/null || echo 'Not available')"